#include "monitor/monitor.h"

DECLARE_STATISTIC_INT32(connect)
DECLARE_STATISTIC_INT32(connect_fail)
DECLARE_STATISTIC_INT32(cost)
DECLARE_STATISTIC_INT32(free_connect)
DECLARE_STATISTIC_INT32(send_success)
DECLARE_STATISTIC_INT32(send_fail)
