/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef meeting_broadcast_CONSTANTS_H
#define meeting_broadcast_CONSTANTS_H

#include "meeting_broadcast_types.h"

namespace lj {

class meeting_broadcastConstants {
 public:
  meeting_broadcastConstants();

};

extern const meeting_broadcastConstants g_meeting_broadcast_constants;

} // namespace

#endif
