/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "meeting_broadcast_constants.h"

namespace lj {

const meeting_broadcastConstants g_meeting_broadcast_constants;

meeting_broadcastConstants::meeting_broadcastConstants() {
}

} // namespace

