/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef post_service_CONSTANTS_H
#define post_service_CONSTANTS_H

#include "post_service_types.h"

namespace lj {

class post_serviceConstants {
 public:
  post_serviceConstants();

};

extern const post_serviceConstants g_post_service_constants;

} // namespace

#endif
