/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "post_service_constants.h"

namespace lj {

const post_serviceConstants g_post_service_constants;

post_serviceConstants::post_serviceConstants() {
}

} // namespace

